#!/bin/bash

for month in 08 09 10
do
    for day in {01..31}
    do
	yday="2019${month}${day}"

    /usr/local/bin/dwcrop /var/ftp/upload/ipcam/$yday/images /mnt/128/dwtl/crop-all/$yday
    /usr/local/bin/dwanno /mnt/128/dwtl/crop-all/$yday
    /usr/local/bin/2dark.sh /mnt/128/dwtl/crop-all/$yday -d 0.35
    mkdir /mnt/128/dwtl/big/$yday
    cp -r /var/ftp/upload/ipcam/$yday/images/* /mnt/128/dwtl/big/$yday
    /usr/local/bin/2dark.sh /mnt/128/dwtl/big/$yday -d 0.35
    /usr/local/bin/dwannobig /mnt/128/dwtl/big/$yday
    echo "2019${month}${day}"
    done
done

