#!/bin/bash

# make a video from images in sourcedir $1
# at rate $2

now=`date +"%Y%m%d-%H%M"`

sourcedir=$1
rate=$2

#sourcedir="/mnt/128/dwtl/crop"
tempdir=`mktemp -d`

if [ -z $sourcedir ]; then exit 0 ; fi
if [ -z $rate ]; then rate=25 ; fi

cp $sourcedir/*/P*.jpg $tempdir

/usr/bin/ffmpeg \
-y -r $rate \
-pattern_type glob -i "${tempdir}/*.jpg" \
-c:v libx264 \
-preset veryfast -an \
-crf 27 \
/mnt/128/dwtl/${now}.mp4

rm -rf $tempdir
