#!/bin/bash

rate=$1
source=$2

yday=`date --date="1 days ago" +"%Y%m%d"`

if [[ ! -d $source ]] ; then exit 0 ; fi

cd $source

/usr/bin/ffmpeg \
-y -r $rate \
-pattern_type glob -i "${source}/*.jpg" \
-c:v libx264 \
-preset veryfast -an \
-crf 27 \
/mnt/128/dwtl/${yday}.mp4
